#!/bin/bash

get_abs_filename() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

create_safelink() {
  if [[ -L "$HOME/$1" ]]; then     # check if dir is a symlink
    rm "$HOME/$1"
  else
    # no, rename old dir
    mv "$HOME/$1" "$HOME/$1_old" 2> /dev/null
  fi
  ## create a link to the config 
  ln -s $(get_abs_filename "$2") "$HOME/$1"
}

# sudo apt install neofetch figlet lolcat exa -y

cd home/.config

for d in */; do
  dir=${d::-1}  # remove ending slash
  create_safelink ".config/$dir" "$dir"
done

cd ..
create_safelink ".bashrc" ".bashrc" 

exit


mv ~/.config/mc ~/.config/mc_old 2> /dev/null
mv ~/.config/herbstluftwm ~/.config/herbstluftwm_old 2> /dev/null
mv ~/.config/neofetch ~/.config/neofetch_old 2> /dev/null
mv ~/.config/alacritty ~/.config/alacritty_old 2> /dev/null
mv ~/.config/nano ~/.config/nano_old 2> /dev/null
mv ~/.bashrc ~/.bashrc_old 2> /dev/null

# symlinking files
ln -s $(get_abs_filename "home/.config/mc") ~/.config/mc
ln -s $(get_abs_filename "home/.config/herbstluftwm") ~/.config/herbstluftwm
ln -s $(get_abs_filename "home/.config/neofetch") ~/.config/neofetch
ln -s $(get_abs_filename "home/.config/alacritty") ~/.config/alacritty
ln -s $(get_abs_filename "home/.config/nano") ~/.config/nano
ln -s $(get_abs_filename "home/.bashrc") ~/.bashrc
