#!/bin/bash
# Installer script for elsni's linux environment
# (w) 2023 by Stephan Elsner

get_abs_filename() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

create_safelink() {
  if [[ -L "$HOME/$1" ]]; then     # check if dir is a symlink
    rm "$HOME/$1"
  else
    # no, rename old dir
    mv "$HOME/$1" "$HOME/$1_old" 2> /dev/null
  fi
  ## create a link to the config
  ln -s $(get_abs_filename "$2") "$HOME/$1"
}


install_dotfiles() {
  cd home/.config

  for d in */; do
    dir=${d::-1}  # remove ending slash
    create_safelink ".config/$dir" "$dir"
  done

  cd ..
  create_safelink ".bashrc" ".bashrc"
  create_safelink ".Xresources" ".Xresources"
  create_safelink ".Xdefaults" ".Xdefaults"
}

install_fira_font() {
  fonts_dir="${HOME}/.local/share/fonts"
  if [ ! -d "${fonts_dir}" ]; then
    mkdir -p "${fonts_dir}"
  fi
  echo "downloading Fira code..."
  version=5.2
  zip=Fira_Code_v${version}.zip
  curl --fail --location --show-error https://github.com/tonsky/FiraCode/releases/download/${version}/${zip} --output ${zip}
  unzip -o -q -d ${fonts_dir} ${zip}
  rm ${zip}
  echo "rebuilding font cache..."
  fc-cache -f
}

# ---------------------- main ------------------------------------------

case "$1" in
  "")
    echo "Install Elsni's linux environment"
    echo "usage: install <OPTION>"
    echo "where OPTION can be:"
    echo "-c   install dotfiles and dependencies for a console-only system (server)"
    echo "-g   install dependencies and dotfiles for a desktop (gui) system"
    echo "-a   install both, console and desktop stuff."
    echo "-d   install dotfiles only, don't install any dependencies"
    exit 0;;
  "-c")
    echo "installing console stuff..."
    sudo apt install neofetch figlet lolcat exa mc nano -y
    install_dotfiles
    exit 0;;
  "-g")
    echo "installing desktop stuff..."
    sudo apt install herbstluftwm polybar alacritty fonts-noto fonts-noto-color-emoji fonts-font-awesome ssh-askpass lxappearance -y
    install_fira_font
    install_dotfiles
    exit 0;;
  "-a")
    echo "installing everything..."
    sudo apt install neofetch figlet lolcat exa mc nano herbstluftwm polybar alacritty fonts-noto fonts-noto-color-emoji fonts-font-awesome ssh-askpass lxappearance -y
    install_fira_font
    install_dotfiles
    exit 0;;
  "-d")
    echo "installing dotfiles only..."
    install_dotfiles
    exit 0;;
  *)
    echo "wrong parameter"
    exit 1;;
esac
