#!/usr/bin/env bash

# theme
xwallpaper --zoom $HOME/.config/herbstluftwm/themes/wallpaper.jpg

export GTK_THEME=Adapta-Nokto:dark

FOCUS='#17C431'

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color $FOCUS
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 0
hc set frame_active_opactiy 1
hc set frame_normal_opacity 0

hc attr theme.title_height 20
#hc attr theme.title_font 'Fira Code:pixelsize=12'  # example using Xft
#hc attr theme.title_font 'Dejavu Sans Bold:pixelsize=12'  # example using Xft
#hc attr theme.title_font '-*-fixed-bold-r-*-*-15-*-*-*-*-*-*-*'
#hc attr theme.title_font '-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*'
hc attr theme.title_font 'Fira Code'
hc attr theme.padding_top 2  # space below the title's baseline (i.e. text depth)
hc attr theme.active.color $FOCUS
hc attr theme.title_color '#000000'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 5
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
