#!/usr/bin/env bash
#############################################################################################################
# herbstluftwm autostart script
#############################################################################################################

WIN=Mod4    # Windows Key is main modifyer
ALT=Mod1    # ALT is 2nd modifyer, mainly for starting apps

# set this to true if you want to save space
# tested on 1024x600 netbook
SMALLSCREEN=false

TERMINAL=alacritty
BROWSER=brave-browser
FILEMANAGER=nemo
MUSICPLAYER=spotify
SETTINGSDIALOG=lxappearance

# colors
FOCUS='#17C431'
BACKGROUND='#5A8E3A'

#############################################################################################################

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid $BACKGROUND

#############################################################################################################
# keybindings
# remove all existing keybindings
hc keyunbind --all

rm -f ~/.config/polybar/config
if [ "$SMALLSCREEN" == "true" ] ; then
    cp ~/.config/polybar/config_small ~/.config/polybar/config
	$TITLEHEIGHT=0
	$BARHEIGHT=20
else
    cp ~/config/polybar/config_large ~/.config/polybar/config
	$TITLEHEIGHT=20
	$BARHEIGHT=32
fi


export GTK_THEME=Adapta-Nokto:dark

hc keybind $WIN-Shift-q quit
hc keybind $WIN-Shift-r reload
hc keybind $WIN-Escape close

# applications
hc keybind $WIN-Return spawn $TERMINAL
hc keybind $WIN-$ALT-b spawn $BROWSER &

# Spotify - Music Player
hc keybind $WIN-$ALT-s spawn $MUSICPLAYER &

# Settings Dialog
hc keybind $WIN-$ALT-l spawn $SETTINGSDIALOG

# File Manager
hc keybind $WIN-$ALT-n spawn $FILEMANAGER

hc keybind $WIN-$ALT-c spawn code &

# Application launcher
hc keybind $WIN-space spawn rofi -modi drun -show drun
 
# basic movement in tiling and floating mode
# focusing clients
hc keybind $WIN-Left  focus left
hc keybind $WIN-Down  focus down
hc keybind $WIN-Up    focus up
hc keybind $WIN-Right focus right

# moving clients in tiling and floating mode
#hc keybind $WIN-Shift-Left  shift left
#hc keybind $WIN-Shift-Down  shift down
#hc keybind $WIN-Shift-Up    shift up
#hc keybind $WIN-Shift-Right shift right
hc keybind $WIN-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $WIN-Shift-Down or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $WIN-Shift-Up or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $WIN-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# splitting frames
# create an empty frame at the specified direction
hc keybind $WIN-u       split   bottom  0.5
hc keybind $WIN-o       split   right   0.5

# let the current frame explode into subframes
hc keybind $WIN-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $WIN-Control-Left    resize left +$resizestep
hc keybind $WIN-Control-Down    resize down +$resizestep
hc keybind $WIN-Control-Up      resize up +$resizestep
hc keybind $WIN-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..6} "code" "brave" "spotify" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$WIN-$key" use_index "$i"
        hc keybind "$WIN-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $WIN-period use_index +1 --skip-visible
hc keybind $WIN-comma  use_index -1 --skip-visible

# layouting
hc keybind $WIN-r remove
hc keybind $WIN-s floating toggle
hc keybind $WIN-f fullscreen toggle
hc keybind $WIN-Shift-f set_attr clients.focus.floating toggle
hc keybind $WIN-Shift-m set_attr clients.focus.minimized true
hc keybind $WIN-Control-m jumpto last-minimized
hc keybind $WIN-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $WIN-a                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# focus
hc keybind $WIN-BackSpace   cycle_monitor
hc keybind $WIN-Tab         cycle_all +1
hc keybind $WIN-Shift-Tab   cycle_all -1
hc keybind $WIN-c cycle
hc keybind $WIN-i jumpto urgent


#############################################################################################################
# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


#############################################################################################################
# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=Code tag=code switchtag=on
hc rule class=Brave-browser tag=brave switchtag=on
hc rule class=Spotify tag=spotify switchtag=on 
hc rule class=Blueman-manager floating=on
hc rule class=Pavucontrol floating=on
hc rule class=FontMaker floating=on


hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

#############################################################################################################
# Screen Setup
# check if HDMI-Display is present
if xrandr -q | grep "HDMI-1 connected"; then
  xrandr --output eDP-1 --off    # Switch off Laptop display
  xrandr --output HDMI-1 --on    # Switch on external display
else
  xrandr --output eDP-1 --on    # Switch on Laptop display
  xrandr --output HDMI-1 --off    # Switch off external display
fi

# shuld find ether laptop display or external display
hc detect_monitors

# make room for polybar
hc pad 0 $BARHEIGHT

# don't use built-in panel
# find the panel
#panel=~/.config/herbstluftwm/scripts/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/scripts/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
#done

#############################################################################################################
# theme

export GTK_THEME=Adapta-Nokto:dark


hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color $FOCUS
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 0
hc set frame_active_opactiy 1
hc set frame_normal_opacity 0

hc attr theme.title_height $TITLEHEIGHT
#hc attr theme.title_font 'Fira Code:pixelsize=12'  # example using Xft
#hc attr theme.title_font 'Dejavu Sans Bold:pixelsize=12'  # example using Xft
#hc attr theme.title_font '-*-fixed-bold-r-*-*-15-*-*-*-*-*-*-*'
#hc attr theme.title_font '-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*'
hc attr theme.title_font 'Fira Code'
hc attr theme.padding_top 2  # space below the title's baseline (i.e. text depth)
hc attr theme.active.color $FOCUS
hc attr theme.title_color '#000000'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 5
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0


#############################################################################################################
# app autostart
xwallpaper --zoom $HOME/.config/herbstluftwm/assets/wallpaper.jpg
hc spawn sh $HOME/.config/polybar/launch.sh
hc spawn nm-applet
hc spawn blueman-applet
