#!/usr/bin/env bash

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
Win=Mod4
Alt=Mod1

hc keybind $Win-Shift-q quit
hc keybind $Win-Shift-r reload
hc keybind $Win-Escape close

# applications
hc keybind $Win-Return spawn "${TERMINAL:-alacritty}" # use your $TERMINAL with xterm as fallback
hc keybind $Win-$Alt-b spawn brave-browser &
hc keybind $Win-$Alt-s spawn spotify &
hc keybind $Win-space spawn rofi -show run
 
# basic movement in tiling and floating mode
# focusing clients
hc keybind $Win-Left  focus left
hc keybind $Win-Down  focus down
hc keybind $Win-Up    focus up
hc keybind $Win-Right focus right

# moving clients in tiling and floating mode
#hc keybind $Win-Shift-Left  shift left
#hc keybind $Win-Shift-Down  shift down
#hc keybind $Win-Shift-Up    shift up
#hc keybind $Win-Shift-Right shift right
hc keybind $Win-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Win-Shift-Down or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Win-Shift-Up or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Win-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# splitting frames
# create an empty frame at the specified direction
hc keybind $Win-u       split   bottom  0.5
hc keybind $Win-o       split   right   0.5

# let the current frame explode into subframes
hc keybind $Win-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Win-Control-h       resize left +$resizestep
hc keybind $Win-Control-j       resize down +$resizestep
hc keybind $Win-Control-k       resize up +$resizestep
hc keybind $Win-Control-l       resize right +$resizestep
hc keybind $Win-Control-Left    resize left +$resizestep
hc keybind $Win-Control-Down    resize down +$resizestep
hc keybind $Win-Control-Up      resize up +$resizestep
hc keybind $Win-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Win-$key" use_index "$i"
        hc keybind "$Win-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Win-period use_index +1 --skip-visible
hc keybind $Win-comma  use_index -1 --skip-visible

# layouting
hc keybind $Win-r remove
hc keybind $Win-s floating toggle
hc keybind $Win-f fullscreen toggle
hc keybind $Win-Shift-f set_attr clients.focus.floating toggle
hc keybind $Win-Shift-m set_attr clients.focus.minimized true
hc keybind $Win-Control-m jumpto last-minimized
hc keybind $Win-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Win-a                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# focus
hc keybind $Win-BackSpace   cycle_monitor
hc keybind $Win-Tab         cycle_all +1
hc keybind $Win-Shift-Tab   cycle_all -1
hc keybind $Win-c cycle
hc keybind $Win-i jumpto urgent


